"""AI - talk to the Adapta models through the Ollama API (stdlib only).

Contextless request (one-shot, nothing remembered):

    import AI
    print(AI.tinker("Give me five taglines for a coffee brand."))

Request with a context object (conversation memory):

    ctx = AI.Context(system="Keep answers short.")
    AI.script("My name is Sam.", context=ctx)
    print(AI.script("What's my name?", context=ctx))   # remembers
    ctx.save("chat.json")                              # optional
    ctx = AI.Context.load("chat.json")

A Context is model-agnostic, so you can pass the same one to different models.

This code was generated by Regular Claude (not claude code)
"""

import json
import os
import urllib.error
import urllib.request

__all__ = [
    "MODELS", "DEFAULT_HOST", "AIError", "Context",
    "ask", "tinker", "script", "module", "goblin",
]

MODELS = {
    "tinker": "adapta-tinker1",
    "script": "adapta-script1",
    "module": "adapta-module1",
    "goblin": "adapta-goblin1",
}

DEFAULT_HOST = "http://localhost:11434"

# Local models can be slow, so the default timeout is generous (seconds).
DEFAULT_TIMEOUT = 600


class AIError(Exception):
    """Raised when a request to the Ollama server fails."""


class Context:
    """A conversation history that can be passed to any request.

    Attributes:
        system:   optional system prompt, sent at the start of every request.
        messages: list of {"role": "user"|"assistant", "content": str}.
    """

    def __init__(self, system=None, messages=None):
        self.system = system
        self.messages = list(messages) if messages else []

    def add(self, role, content):
        if role not in ("user", "assistant"):
            raise ValueError("role must be 'user' or 'assistant'")
        self.messages.append({"role": role, "content": content})

    def clear(self):
        """Forget the conversation but keep the system prompt."""
        self.messages.clear()

    def copy(self):
        """Return an independent copy, handy for branching a conversation."""
        return Context(self.system, self.messages)

    def to_messages(self):
        """Full message list in Ollama chat format."""
        out = []
        if self.system:
            out.append({"role": "system", "content": self.system})
        out.extend(self.messages)
        return out

    def to_dict(self):
        return {"system": self.system, "messages": self.messages}

    @classmethod
    def from_dict(cls, data):
        return cls(data.get("system"), data.get("messages"))

    def save(self, path):
        with open(path, "w", encoding="utf-8") as f:
            json.dump(self.to_dict(), f, indent=2, ensure_ascii=False)

    @classmethod
    def load(cls, path):
        with open(path, encoding="utf-8") as f:
            return cls.from_dict(json.load(f))

    def __len__(self):
        return len(self.messages)

    def __repr__(self):
        return f"Context(system={self.system!r}, messages={len(self.messages)})"


def _resolve_model(model):
    """Accept 'tinker' or 'adapta-tinker1' (case-insensitive)."""
    key = model.strip().lower()
    if key in MODELS:
        return MODELS[key]
    if key in MODELS.values():
        return key
    valid = ", ".join(list(MODELS) + list(MODELS.values()))
    raise ValueError(f"Unknown model {model!r}. Valid names: {valid}")


def _post(url, payload, timeout):
    req = urllib.request.Request(
        url,
        data=json.dumps(payload).encode("utf-8"),
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        return urllib.request.urlopen(req, timeout=timeout)
    except urllib.error.HTTPError as e:
        try:
            detail = json.loads(e.read().decode("utf-8")).get("error", "")
        except (ValueError, OSError):
            detail = ""
        raise AIError(f"HTTP {e.code} {e.reason}: {detail}".rstrip(": ")) from e
    except urllib.error.URLError as e:
        raise AIError(f"Could not reach Ollama at {url}: {e.reason}") from e
    except TimeoutError as e:
        raise AIError(f"Request to {url} timed out after {timeout}s") from e


def _read_reply(resp, stream, on_token, chat):
    """Collect the reply text from a streaming or non-streaming response."""
    def piece(obj):
        if chat:
            return (obj.get("message") or {}).get("content", "")
        return obj.get("response", "")

    try:
        with resp:
            if not stream:
                obj = json.loads(resp.read().decode("utf-8"))
                if "error" in obj:
                    raise AIError(obj["error"])
                return piece(obj)

            parts = []
            for raw in resp:
                raw = raw.strip()
                if not raw:
                    continue
                obj = json.loads(raw.decode("utf-8"))
                if "error" in obj:
                    raise AIError(obj["error"])
                text = piece(obj)
                if text:
                    parts.append(text)
                    if on_token:
                        on_token(text)
                if obj.get("done"):
                    break
            return "".join(parts)
    except TimeoutError as e:
        raise AIError("Timed out while waiting for the model's reply") from e
    except ValueError as e:
        raise AIError(f"Invalid response from server: {e}") from e


def ask(model, prompt, context=None, system=None, host=None,
        timeout=DEFAULT_TIMEOUT, stream=False, on_token=None,
        think=None, options=None):
    """Send a prompt to an Adapta model and return the reply text.

    Args:
        model:    'tinker', 'script', 'module', 'goblin', or a full name
                  such as 'adapta-module1'.
        prompt:   the user message.
        context:  optional Context. If given, the conversation so far is sent
                  and the new prompt/reply are appended to it on success.
                  If omitted, the request is contextless (nothing remembered).
        system:   system prompt for a contextless request. With a context,
                  set context.system instead (this argument is ignored).
        host:     Ollama base URL. Defaults to $OLLAMA_HOST or localhost.
        timeout:  seconds to wait for the server.
        stream:   stream tokens as they are generated.
        on_token: callback called with each chunk of text when stream=True.
        think:    True/False to turn a model's reasoning on or off, if the
                  model supports it. None leaves it to the model's default.
        options:  dict of Ollama model options, e.g. {"temperature": 0.2}.
    """
    model = _resolve_model(model)
    host = _resolve_host(host)

    if context is not None:
        messages = context.to_messages()
    else:
        messages = [{"role": "system", "content": system}] if system else []
    messages.append({"role": "user", "content": prompt})

    payload = {"model": model, "messages": messages, "stream": bool(stream)}
    if think is not None:
        payload["think"] = bool(think)
    if options:
        payload["options"] = options

    resp = _post(host + "/api/chat", payload, timeout)
    reply = _read_reply(resp, stream, on_token, chat=True)

    if context is not None:
        context.add("user", prompt)
        context.add("assistant", reply)
    return reply


def _resolve_host(host):
    host = host or os.environ.get("OLLAMA_HOST") or DEFAULT_HOST
    if "://" not in host:
        host = "http://" + host
    return host.rstrip("/")


def _shortcut(name):
    def call(prompt, context=None, **kwargs):
        return ask(name, prompt, context=context, **kwargs)
    call.__name__ = name
    call.__doc__ = f"Ask {MODELS[name]}. Same arguments as ask(), minus the model."
    return call


tinker = _shortcut("tinker")
script = _shortcut("script")
module = _shortcut("module")
goblin = _shortcut("goblin")


if __name__ == "__main__":
    # Tiny interactive chat:  python AI.py [tinker|script|module|goblin]
    import sys

    name = sys.argv[1] if len(sys.argv) > 1 else "script"
    chat = Context()
    print(f"Chatting with {_resolve_model(name)}. Blank line to quit.")
    try:
        while True:
            line = input("> ").strip()
            if not line:
                break
            ask(name, line, context=chat, stream=True,
                on_token=lambda t: print(t, end="", flush=True))
            print()
    except (AIError, EOFError, KeyboardInterrupt) as e:
        print(f"\n{e}" if isinstance(e, AIError) else "")